# Generated by Django 3.1.5 on 2021-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('artname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('available', models.IntegerField(default=1)),
                ('username', models.CharField(default='NOT SOLD', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
